# .rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'lib/geocoder/lookups/geoapify.rb'
    - 'lib/geocoder/results/geoapify.rb'

Rails:
  Enabled: true
