require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
    - 'app/services/geolocation_service.rb'
    - 'db/*.rb'